default-active-mission-limit-at-once: 10000
database:
  remove_inactive_user_after_days: 365
default-mission-start-message:
- '&aMissione &9&l{name} &a➤ Iniziata!'
default-mission-complete-message:
- '&aMissione &9&l{name} &a➤ Completata!'
default-mission-fail-message:
- '&cMissione &9&l{name} &c➤ Fallita!'
default-mission-pause-message:
- '&9Missione &9&l{name} &9➤ In Pausa!'
default-mission-unpause-message:
- '&9Missione &9&l{name} &9➤ Riattivata!'
quest-display-defaults:
  locked:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: RED_STAINED_GLASS_PANE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        Unbreakable: true
    description:
    - '&4&l&m---&8&l&m[--&8      &m*-----*&8    &l&m--]&4&l&m---'
    - ''
    - '&4➤ &9{name} &4&lBloccata'
    - ''
    - '{foreach-uncompleted-require}&4➤ Bloccata'
    - ''
    - '&4&l&m---&8&l&m[--&8      &m*-----*&8    &l&m--]&4&l&m---'
    hide: true
  unstarted:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: BOOK
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        Unbreakable: true
    description:
    - '&9&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&9&l&m---'
    - '&9➤ {name}'
    - ''
    - '&7➤ Missioni completate: &e{completed-missions-amount}&9/{missions-amount}'
    - ''
    - '&9&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&9&l&m---'
    hide: false
  onprogress:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: WRITABLE_BOOK
      meta:
        ==: ItemMeta
        meta-type: BOOK
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        Unbreakable: true
    description:
    - '&9&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&9&l&m---'
    - '&9➤ {name}'
    - ''
    - '&7➤ Missioni completate: &e{completed-missions-amount}&9/{missions-amount}'
    - ''
    - '&9&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&9&l&m---'
    hide: false
  cooldown:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: ORANGE_STAINED_GLASS_PANE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        Unbreakable: true
    description:
    - '&6&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&6&l&m---'
    - '&6➤ {name}'
    - ''
    - '&7➤ In cooldown per {cooldown-left}'
    - ''
    - '&6&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&6&l&m---'
    hide: false
  failed:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: BLACK_STAINED_GLASS_PANE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        Unbreakable: true
    description:
    - '&4&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&4&l&m---'
    - '&4➤ {name}'
    - ''
    - '&4➤ Fallita!'
    - ''
    - '&4&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&4&l&m---'
    hide: true
  completed:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: ENCHANTED_BOOK
      meta:
        ==: ItemMeta
        meta-type: ENCHANTED
        ItemFlags:
        - HIDE_ENCHANTS
        - HIDE_ATTRIBUTES
        - HIDE_UNBREAKABLE
        - HIDE_DESTROYS
        - HIDE_PLACED_ON
        - HIDE_POTION_EFFECTS
        Unbreakable: true
    description:
    - '&2&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&2&l&m---'
    - '&2➤ {name}'
    - ''
    - '&2➤ Completata'
    - ''
    - '&2&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&2&l&m---'
    hide: false
mission-display-defaults:
  locked:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: BLACK_DYE
    description:
    - '&4&l&m---&8&l&m[--&8      &m*-----*&8    &l&m--]&4&l&m---'
    - ''
    - '&4➤ &4&lBloccata'
    - ''
    - '&4&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&4&l&m---'
    hide: true
  unstarted:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: GRAY_DYE
    description:
    - '&9&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&9&l&m---'
    - '&9{name}'
    - ''
    - '{foreach-task}&7➤ {unstarted-description}'
    - ''
    - '&9&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&9&l&m---'
    hide: false
  onprogress:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: LIGHT_BLUE_DYE
    description:
    - '&9&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&9&l&m---'
    - '&9{name}'
    - ''
    - '{foreach-task}&7➤ {task-status}'
    - ''
    - '&9&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&9&l&m---'
    hide: false
  cooldown:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: ORANGE_DYE
    description:
    - '&6&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&6&l&m---'
    - '&6{name}'
    - ''
    - '&7➤ In cooldown per {cooldown-left}'
    - ''
    - '&6&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&6&l&m---'
    hide: false
  failed:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: RED_DYE
    description:
    - '&4&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&4&l&m---'
    - '&4{name}'
    - ''
    - '&4➤ Fallita!'
    - ''
    - '&4&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&4&l&m---'
    hide: true
  completed:
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: LIME_DYE
    description:
    - '&2&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&2&l&m---'
    - '&2{name}'
    - ''
    - '&2➤ Completata'
    - ''
    - '&2&l&m---&8&l&m[--&8      &m*-----*&8      &l&m--]&2&l&m---'
    hide: false
priority: 0