# Those are default values each new task type will inherit those values
# and each new task will inherit his task type default values
# any value shall be modified later to a non default value

# Duration of bar (20 ticks = 1 second)
ticks-duration: 70

# Color of the bar
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
default-color: BLUE

# type of the bar
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
default-style: SEGMENTED_20

# should the bar be shown?
default-show-bossbar: true